/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsSplatRouteImport } from './routes/blogs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as LlmsDotmdxBlogsSplatRouteImport } from './routes/llms[.]mdx.blogs.$'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiPortfolioChatRouteImport } from './routes/api.portfolio.chat'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSplatRoute = BlogsSplatRouteImport.update({
  id: '/blogs/$',
  path: '/blogs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDotmdxBlogsSplatRoute = LlmsDotmdxBlogsSplatRouteImport.update({
  id: '/llms.mdx/blogs/$',
  path: '/llms.mdx/blogs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioChatRoute = ApiPortfolioChatRouteImport.update({
  id: '/api/portfolio/chat',
  path: '/api/portfolio/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/projects': typeof ProjectsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/search': typeof ApiSearchRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/api/portfolio/chat': typeof ApiPortfolioChatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/llms.mdx/blogs/$': typeof LlmsDotmdxBlogsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/projects': typeof ProjectsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/search': typeof ApiSearchRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/api/portfolio/chat': typeof ApiPortfolioChatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/llms.mdx/blogs/$': typeof LlmsDotmdxBlogsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/projects': typeof ProjectsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/search': typeof ApiSearchRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/api/portfolio/chat': typeof ApiPortfolioChatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/llms.mdx/blogs/$': typeof LlmsDotmdxBlogsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/llms-full.txt'
    | '/projects'
    | '/api/$'
    | '/api/search'
    | '/blogs/$'
    | '/api/portfolio/chat'
    | '/api/rpc/$'
    | '/llms.mdx/blogs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/llms-full.txt'
    | '/projects'
    | '/api/$'
    | '/api/search'
    | '/blogs/$'
    | '/api/portfolio/chat'
    | '/api/rpc/$'
    | '/llms.mdx/blogs/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/llms-full.txt'
    | '/projects'
    | '/api/$'
    | '/api/search'
    | '/blogs/$'
    | '/api/portfolio/chat'
    | '/api/rpc/$'
    | '/llms.mdx/blogs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  ProjectsRoute: typeof ProjectsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiSearchRoute: typeof ApiSearchRoute
  BlogsSplatRoute: typeof BlogsSplatRoute
  ApiPortfolioChatRoute: typeof ApiPortfolioChatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  LlmsDotmdxBlogsSplatRoute: typeof LlmsDotmdxBlogsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$': {
      id: '/blogs/$'
      path: '/blogs/$'
      fullPath: '/blogs/$'
      preLoaderRoute: typeof BlogsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.mdx/blogs/$': {
      id: '/llms.mdx/blogs/$'
      path: '/llms.mdx/blogs/$'
      fullPath: '/llms.mdx/blogs/$'
      preLoaderRoute: typeof LlmsDotmdxBlogsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/chat': {
      id: '/api/portfolio/chat'
      path: '/api/portfolio/chat'
      fullPath: '/api/portfolio/chat'
      preLoaderRoute: typeof ApiPortfolioChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  ProjectsRoute: ProjectsRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiSearchRoute: ApiSearchRoute,
  BlogsSplatRoute: BlogsSplatRoute,
  ApiPortfolioChatRoute: ApiPortfolioChatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  LlmsDotmdxBlogsSplatRoute: LlmsDotmdxBlogsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
